title: Group Industrial Project 2018-19
author: VR Melanathuru
Group Members: Tom Wilkinson, Lucian Cabrini, James Foster, Kenneth Chotitawan

#Build Settings
markdown: maruku
theme: minima

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
